WebCrawler/WebCrawler.WebView/ViewModels/ErrorViewModel.cs
namespace WebCrawler.Presentation.WebView.ViewModels;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

WebCrawler/WebCrawler.WebView/Controllers/CrawlResultsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebCrawler.Application;

namespace WebCrawler.Presentation.WebView.Controllers;

public class CrawlResultsController : Controller
{
    private readonly CrawlerService _crawlerService;

    public CrawlResultsController(CrawlerService crawlerService)
    {
        _crawlerService = crawlerService;
    }

    public async Task<IActionResult> Index(int id)
    {
        var crawledSiteResult = await _crawlerService.GetCrawledSiteResultsAsync(id);
        return View(crawledSiteResult);
    }
}

WebCrawler/WebCrawler.WebView/Controllers/CrawledSitesController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using WebCrawler.Application;
using WebCrawler.Presentation.WebView.ViewModels;

namespace WebCrawler.Presentation.WebView.Controllers;

public class CrawledSitesController : Controller
{
    private readonly CrawlerService _crawlerService;

    public CrawledSitesController(CrawlerService crawlerService)
    {
        _crawlerService = crawlerService;
    }

    public IActionResult Index(int pageNumber, int pageSize)
    {
        var crawledSites = _crawlerService.GetCrawledSitesPagedList(pageNumber, pageSize);

        return View(crawledSites);
    }

    public async Task<IActionResult> CrawlSite(string input)
    {
        try
        {
            if (string.IsNullOrWhiteSpace(input))
            {
                throw new Exception("Empty input value.");
            }

            await _crawlerService.CrawlSiteAsync(input);

            return Redirect("Index");

        }
        catch (Exception ex)
        {
            return View("CrawlerError", ex.Message);
        }
    }

    public IActionResult Error()
    {
        return View(new ErrorViewModel
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
        });
    }
}

WebCrawler/WebCrawler.WebView/Views/CrawlResults/Index.cshtml
@model WebCrawler.Application.Models.CrawledSiteDto


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.Url</h2>
        </div>
    </div>
    <br />
    <h2>Perfomance</h2>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Url
                </th>
                <th>
                    Timings(ms)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var crawledSiteResult in Model.SiteCrawlResults)
            {
                <tr>
                    <td>
                        @crawledSiteResult.Url
                    </td>
                    <td>@crawledSiteResult.ResponseTimeMs</td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    @if (Model.OnlySitemapResults.Any())
    {
        <h2>Urls not found at website :</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Url
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var crawledSiteResult in Model.OnlySitemapResults)
                {
                    <tr>
                        <td>
                            @crawledSiteResult.Url
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    @if (!Model.OnlySitemapResults.Any())
    {
        <h3 class="text-body">Urls list founded in sitemap.xml but not founded after crawling a website is empty.</h3>
    }
    <br />
    @if (Model.OnlySiteResults.Any())
    {
        <h2>Urls not found at sitemap.xml :</h2>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Url
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var crawledSiteResult in Model.OnlySiteResults)
                {
                    <tr>
                        <td width="100%">
                            @crawledSiteResult.Url
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    @if (!Model.OnlySiteResults.Any())
    {
        <h3 class="text-body">Urls list founded by crawling the website but not in sitemap.xml is empty.</h3>
    }
</div>

WebCrawler/WebCrawler.WebView/Views/CrawlResults/SiteCrawlResult.cshtml
@model WebCrawler.WebView.Logic.ViewModels.CrawledSiteViewModel


<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">@Model.Url</h2>
        </div>
    </div>
    <br />
    <h2>Perfomance</h2>
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Url
                </th>
                <th>
                    Timings(ms)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model.SiteCrawlResult)
            {
                <tr>
                    <td width="70%">
                        @obj.Url
                    </td>
                    <td width="30%">@obj.ResponseTimeMs</td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    @if (Model.OnlySitemapResults.Any())
    {
        <h2>Urls not found at website :</h2>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Url
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var obj in Model.OnlySitemapResults)
                {
                    <tr>
                        <td width="100%">
                            @obj.Url
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }

    @if (!Model.OnlySitemapResults.Any())
    {

        <h3 width="100%">Urls list founded in sitemap.xml but not founded after crawling a website is empty.</h3>

    }
    <br />
    @if (Model.OnlySiteResults.Any())
    {
        <h2>Urls not found at sitemap.xml :</h2>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Url
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var obj in Model.OnlySiteResults)
                {
                    <tr>
                        <td width="100%">
                            @obj.Url
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    @if (!Model.OnlySiteResults.Any())
    {
        <h3 width="100%">Urls list founded by crawling the website but not in sitemap.xml is empty.</h3>
    }
</div>

WebCrawler/WebCrawler.WebView/Views/CrawledSites/CrawlError.cshtml
@model string

@{
    ViewData["Title"] = "Error";
}

<h2 class="text-danger">Error.</h2>

<h3 class="text-black"><strong>Detrails :</strong> "@Model"</h3>

WebCrawler/WebCrawler.WebView/Views/CrawledSites/CrawlerError.cshtml
@model string

@{
    ViewData["Title"] = "Error";
}

<h2 class="text-danger">Error.</h2>

<h3 class="text-black"><strong>Details :</strong> "@Model"</h3>

WebCrawler/WebCrawler.WebView/Views/CrawledSites/Index.cshtml
@using WebCrawler.Application.Helpers;
@using WebCrawler.Application.Models;
@model PagedList<CrawledSiteDto>

<div class="container">
    <div class="row">
        @using (Html.BeginForm("CrawlSite", "CrawledSites"))
        {
            <table class="table-borderless">
                <tr>
                    <td> Enter a website: </td>
                    <td> <input type="text" name="input" /></td>
                    <td> <input class="btn btn-primary" type="submit" value="Test" /></td>
                </tr>
            </table>
        }
    </div>
    <br />
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Test Results </h2>
        </div>
    </div>
    <br />
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>
                    Url
                </th>
                <th>
                    Date
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var crawledSite in Model.Items)
            {
                <tr>
                    <td>
                        @crawledSite.Url
                    </td>
                    <td>@crawledSite.CrawlDate</td>
                    <td align="center">
                        <a asp-controller="CrawlResults" asp-action="Index" asp-route-Id="@crawledSite.Id" class="btn btn-primary">Show Details</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <div>
        @if (Model.HasPreviousPage)
        {
            <a asp-controller="CrawledSites" asp-action="Index"
           asp-route-pageNumber="@(Model.PageNumber - 1)" class="btn btn-primary"> Previous </a>
        }
        @if (!Model.HasPreviousPage)
        {
            <button class="btn btn-dark"> Previous </button>
        }
        @if (Model.HasNextPage)
        {
            <a asp-controller="CrawledSites" asp-action="Index"
           asp-route-pageNumber="@(Model.PageNumber + 1)" class="btn btn-primary"> Next </a>
        }
        @if (!Model.HasNextPage)
        {
            <button class="btn btn-dark"> Next </button>
        }
    </div>
</div>

WebCrawler/WebCrawler.WebView/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebCrawler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebCrawler.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="CrawledSites" asp-action="Index">WebCrawler</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>